import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-full bg-[#f6f1ed] text-foreground`}
      >
        <div className="flex min-h-screen items-center justify-center px-4 py-8">
          <div className="relative w-full max-w-[430px] overflow-hidden rounded-[2.5rem] border border-[#ffd1aa] bg-white shadow-[0_25px_60px_-20px_rgba(243,152,118,0.45)]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
